image:
  file: .gitpod.dockerfile
ports:
    - port: 5000
      onOpen: open-preview
tasks:
    - init: >
        python3 -m venv venv && source venv/bin/activate && pip install -r requirements.txt;
    - command: python3 -m venv venv && source venv/bin/activate && pip install -r requirements.txt;
      command: export FLASK_APP=main.py && export FLASK_ENV=development && export FLASK_DEBUG=1 && python3 -m flask run
