image:
  file: .gitpod.dockerfile
ports:
    - port: 5000
      onOpen: open-preview
tasks:
    - init: >
        pip install --upgrade pip;
        pip3 install --upgrade pip;
        pip3 install -r requirements.txt;
    - command: >
        mysqld;
    - command: >
        pip3 install -r requirements.txt;
        export FLASK_APP=main.py;
        export FLASK_ENV=development;
        export FLASK_DEBUG=1;
        python3 -m flask run;
