image:
  file: .gitpod.dockerfile
ports:
    - port: 5000
      onOpen: open-preview
tasks:
    - init: >
        python3 -m venv venv
        source venv/bin/activate
        pip3 install -r requirements.txt
        mysql -u root -e "CREATE DATABASE example";
        
    - command: >
        source venv/bin/activate
        export FLASK_APP=main.py
        export FLASK_ENV=development
        export FLASK_DEBUG=1
        python3 -m flask run
        gp preview $(gp url 5000)